import "./program.css"
import Link from "next/link"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import {
	faListCheck,
	faCommentDots,
	faCircleCheck,
} from "@fortawesome/free-solid-svg-icons"
import NavProgram from "@/components/program/nav"
import CardProgram from "@/components/program/card"

export const metadata = {
	title: "Program | Bijakcuan.",
	description: "Generated by create next app",
}

export default function Program() {
	return (
		<main id="program">
			<section
				id="hero"
				style={{ backgroundImage: "url(/assets/program/hero-bg.png)" }}>
				<div className="container d-flex align-items-center justify-content-center">
					<div className="d-block text-center">
						<h1>Pelatihan Keuangan Untuk Sukses Finansial</h1>
						<p>Majukan Bisnismu Dengan Pengelolaan Keuangan Yang Baik</p>
						<Link href={"#content"} className="btn btn-primary">
							Gabung Sekarang
						</Link>
					</div>
				</div>
			</section>
			<section id="program-benefit">
				<div className="container">
					<div className="row gap-5">
						<div className="col d-flex align-items-center gap-3">
							<FontAwesomeIcon icon={faListCheck} />
							<p>
								Materi Dari <b>Para Expert</b> Dibidang Keuangan
							</p>
						</div>
						<div className="col d-flex align-items-center gap-3">
							<FontAwesomeIcon icon={faCommentDots} />
							<p>
								Konsultasi Kendala Keuanganmu <b>Bersama Ahli</b>
							</p>
						</div>
						<div className="col d-flex align-items-center gap-3">
							<FontAwesomeIcon icon={faCircleCheck} />
							<p>
								Data Yang Aktual Berdasarkan <b>Riset Mendalam</b>
							</p>
						</div>
					</div>
				</div>
			</section>
			<section id="content">
				<div className="container">
					<div className="row gap-5">
						<div className="col">
							<NavProgram></NavProgram>
						</div>
						<div className="col-lg-5">
							<CardProgram></CardProgram>
						</div>
					</div>
				</div>
			</section>
		</main>
	)
}
